apiVersion: apps/v1
kind: Deployment
metadata:
  name: manki-playground
spec:
  selector:
    matchLabels:
      app: manki-playground
  replicas: 1
  template:
    metadata:
      labels:
        app: manki-playground
    spec:
      containers:
      - name: manki-playground
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
