apiVersion: v1
kind: Service
metadata:
  name: manki-playground-service
spec:
  type: ClusterIP
  selector:
    app: manki-playground
  ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: 8888
