SERVER_IP = "192.168.56.110"
SERVER_NAME = "mankiS"
SERVER_SCRIPT = <<-SHELL
  echo ">>>> START SERVER SCRIPT <<<<"
  export INSTALL_K3S_EXEC="--flannel-iface=eth1"
  export K3S_KUBECONFIG_MODE='644'
  sudo -i && apt update 2>/dev/null && apt install -y curl 2>/dev/null && curl -sfL https://get.k3s.io |  sh -
  kubectl apply -f /vagrant_shared/scripts/app1.yaml
  kubectl apply -f /vagrant_shared/scripts/app2.yaml
  kubectl apply -f /vagrant_shared/scripts/app3.yaml
  kubectl apply -f /vagrant_shared/scripts/ingress.yaml
  echo ">>>> END SERVER SCRIPT <<<<"
  SHELL

MEMORY = "4096"
CPUS = "4"

Vagrant.configure(2) do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.define SERVER_NAME do |mankiS|
    mankiS.vm.hostname = SERVER_NAME
    mankiS.vm.network "private_network", ip: SERVER_IP
    mankiS.vm.synced_folder "./shared", "/vagrant_shared"
    mankiS.vm.provider "virtualbox" do |vb|
      vb.name = SERVER_NAME
      vb.memory = MEMORY
      vb.cpus = CPUS
    end
    mankiS.vm.provision "shell", inline: SERVER_SCRIPT
  end

end
