SERVER_IP = "192.168.56.110"
SERVER_NAME = "mankiS"
SERVER_SCRIPT = <<-SHELL
  echo ">>>> START SERVER SCRIPT => for mankiS"
  export INSTALL_K3S_EXEC="--bind-address=#{SERVER_IP} --node-external-ip=#{SERVER_IP} --flannel-iface=eth1"
  export K3S_KUBECONFIG_MODE='644'
  sudo -i && apt-get update && apt-get install -y curl && curl -sfL https://get.k3s.io |  sh -
  cp /var/lib/rancher/k3s/server/node-token /vagrant_shared/token
  echo ">>>> END SERVER SCRIPT => for mankiS"
  SHELL

WORKER_IP = "192.168.56.111"
WORKER_NAME = "mankiSW"
WORKER_SCRIPT = <<-SHELL
  echo ">>>> START WORKER SCRIPT => for mankiSW"
  export K3S_TOKEN_FILE=/vagrant_shared/token
  export K3S_URL=https://#{SERVER_IP}:6443
  export INSTALL_K3S_EXEC="--flannel-iface=eth1"
  sudo -i && apt-get update && apt-get install -y curl && curl -sfL https://get.k3s.io | sh -
  echo ">>>> END WORKER SCRIPT => for mankiSW"
  SHELL


MEMORY = "2048"
CPUS = "1"

Vagrant.configure(2) do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.box_url = "https://app.vagrantup.com/debian/boxes/bullseye64/versions/11.20221219.1/providers/virtualbox.box"

  config.vm.define SERVER_NAME do |mankiS|
    mankiS.vm.hostname = SERVER_NAME
    mankiS.vm.network "private_network", ip: SERVER_IP
    mankiS.vm.synced_folder "./shared", "/vagrant_shared"
    mankiS.vm.provider "virtualbox" do |vb|
      vb.name = SERVER_NAME
      vb.memory = MEMORY
      vb.cpus = CPUS
    end
    mankiS.vm.provision "shell", inline: SERVER_SCRIPT
  end

  config.vm.define WORKER_NAME do |mankiSW|
    mankiSW.vm.hostname = WORKER_NAME
    mankiSW.vm.network "private_network", ip: WORKER_IP
    mankiSW.vm.synced_folder "./shared", "/vagrant_shared"
    mankiSW.vm.provider "virtualbox" do |vb|
      vb.name = WORKER_NAME
      vb.memory = MEMORY
      vb.cpus = CPUS
    end
    mankiSW.vm.provision "shell", inline: WORKER_SCRIPT
  end
end
