########################################
#               Service                #
########################################

apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  type: ClusterIP
  selector:
    app: iot-app1
  ports:
    - name: http
      port: 80
      targetPort: 8080

########################################
#              Deployement             #
########################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: iot-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-app1
  template:
    metadata:
      labels:
        app: iot-app1
    spec:
      containers:
      - name: hello-kubernetes
        image: paulbouwer/hello-kubernetes:1.10
        ports:
          - containerPort: 8080
        env: 
        - name: MESSAGE
          value: "Hello from app1."
